### PR TITLE
Issue 7

### PR DESCRIPTION
**Pull request by lausuarez02**
### [Issue-7](https://github.com/bgwebagency/redesigner.io/issues/7) 

- [x] Add feature of img instead of button
- [x] Improve img adding dynamic loading with next/image
- [x] Add usePathname to get the pathname and be able to get the current route

### CODE REVIEW

**Review by kirandash — CHANGES_REQUESTED** [review]
@lausuarez02 Thanks for the PR but the images are stretched since the height, width are 500px. Can you please change it to 100px and align properly to centre 

or 

you can review PR: https://github.com/bgwebagency/redesigner.io/pull/50

by @GrumpyArdias since that PR already seems to fix the problem. 

I will let you decide since the issue is assigned to you. Thanks 🙏🏻

**Comment by lausuarez02** [comment]
Fix the height and weight and merge conflicts.

**Comment by kirandash** [comment]
> Fix the height and weight and merge conflicts.

Please align the images to centre as well

It's not aligned properly

image

Tips for future PR 💡: Please add a screenshot of the result if applicable so that it helps while reviewing the changes

**Comment by lausuarez02** [comment]
I can not upload a photo right now but i've fixed the error

**Review by kirandash — APPROVED** [review]

**Pull request merged**
